### ISSUE TITLE
[babel-preset] Old config for babel-preset-env

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-libs#215]
https://github.com/cozy/cozy-libs/blob/cb6591132bec425078c11ad784b6005208b57305/packages/babel-preset-cozy-app/index.js#L5-L14

We dropped support for IE11 and chrome 42 (https://paper.dropbox.com/doc/Arret-IE11-uc6IozUVabnpGDFKhr85O).

**Comment by edas** [comment]
And:
* last ESR of Firefox is 60 so we probably should use that one instead of 40
* 'last 2 versions' is also matching with Opera, Blackberry, Samsung and IE10. We should probably focus more.

Something like:
* last 2 Chrome major versions
* last 2 ChromeAndroid major versions
* last 2 Firefox major versions
* last 2 FirefoxAndroid major versions
* last 2 Safari major versions
* last 2 iOS major versions
* last 2 Edge major versions
